apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: s{{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - name: {{ .Values.application.name }}
        image: {{ .Values.image.repository}}:{{ .Values.image.tag}}
        ports:
        - containerPort: {{ .Values.application.containerPort }}
