replicaCount: 1
application: 
  name: shared-library-app
  containerPort: 5001

image:
  repository: malamcsc/shared-library-app
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
