name: Trigger Pipeline on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  trigger-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Pipeline Job
      env:
        JENKINS_URL: http://localhost:8080
        JENKINS_USER: alam
        JENKINS_TOKEN: ${{ env.JENKINS_TOKEN }}
      run: |
        curl -X POST "http://localhost:8080/job/flask" \
        --user "alam:11144cf3d2841fcc869d342bbb9bc433e9"
