name: Trigger Pipeline on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  trigger-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Pipeline Job
      env:
        JENKINS_URL: ${{ env.JENKINS_URL }}
        JENKINS_USER: ${{ env.JENKINS_USER }}
        JENKINS_TOKEN: ${{ env.JENKINS_TOKEN }}
      run: |
        curl -X POST "${{ env.JENKINS_URL }}/job/flask" \
        --user "${{ env.JENKINS_USER }}:${{ env.JENKINS_TOKEN }}"
