name: Trigger Pipeline on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  trigger-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Trigger Jenkins Pipeline Job
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      run: |
        curl -X POST "${{ secrets.JENKINS_URL }}/job/<JOB_NAME>/build" \
        --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"
